
/* AUTO GENERATED FILE, DO NOT EDIT THIS FILE */
#ifndef VERSION_H_
#define VERSION_H_

/**
 * Major version definition. Incremented manually.
 */
#define MAJOR_VERSION 		1

/**
 * Minor version definition. Incremented manually.
 */
#define MINOR_VERSION 		0

/**
 * Build version definition. Incremented automatically at rebuild.
 */
#define BUILD_VERSION		7

/**
 * Software version in string format. Build automatically at rebuild.
 */
#define VERSION_STRING	"1.0.7"

/**
 * Build timestamp definition. Set automatically at rebuild.
 */
#define BUILD_TIMESTAMP		"2023-09-14 15:48:11"

#endif /* VERSION_H_ */
